namespace DomainBlocks.EventStore.Primitives.Identity;

public static class NamespaceIds
{
    private const string Prefix = "domainblocks";

    /// <summary>
    /// Root namespace for all deterministic UUID version 5 values generated by DomainBlocks.
    /// </summary>
    /// <remarks>
    /// Changing this value is a breaking change and will invalidate all previously generated deterministic identifiers.
    /// </remarks>
    public static readonly Guid Root = Guid.Parse("473d6864-62f3-4d18-ab08-914990bae65e");

    /// <summary>
    /// Namespace for deterministic event identifiers.
    /// </summary>
    public static readonly Guid Events = Guid.CreateVersion5(Root, $"{Prefix}/events/v1");
}