<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
    <PackageReference Include="KurrentDB.Client" Version="1.0.0"/>
    <PackageReference Include="NUnit" Version="4.4.0"/>
    <PackageReference Include="Shouldly" Version="4.3.0"/>
    <PackageReference Include="System.Linq.Async" Version="6.0.3"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DomainBlocks.EventStore.KurrentDB\DomainBlocks.EventStore.KurrentDB.csproj"/>
    <ProjectReference Include="..\DomainBlocks.Testing.Integration\DomainBlocks.Testing.Integration.csproj"/>
  </ItemGroup>
  
</Project>
