services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - "27017:27017"
    command: [ "--replSet", "rs0", "--bind_ip", "localhost,mongo1", "--port", "27017" ]
    volumes:
      - mongo1-data:/data/db
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - "27018:27018"
    command: [ "--replSet", "rs0", "--bind_ip", "localhost,mongo2", "--port", "27018" ]
    volumes:
      - mongo2-data:/data/db
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:latest
    container_name: mongo3
    ports:
      - "27019:27019"
    command: [ "--replSet", "rs0", "--bind_ip", "localhost,mongo3", "--port", "27019" ]
    volumes:
      - mongo3-data:/data/db
    networks:
      - mongo-cluster
  
  mongo-init-rs:
    image: mongo:latest
    container_name: mongo-init-rs
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts/init-mongo-replica-set.sh:/init-mongo-replica-set.sh:ro
    command: [ "bash", "/init-mongo-replica-set.sh" ]
    networks:
      - mongo-cluster
    restart: "no"
  
  kurrent-db:
    image: kurrentplatform/kurrentdb:latest
    container_name: domain-blocks-kurrent-db
    ports:
      - "2113:2113"
    command: [ "--insecure" ]
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeit
      - KURRENTDB_LOG_LEVEL=VERBOSE

volumes:
  mongo-data:
  mongo1-data:
  mongo2-data:
  mongo3-data:

networks:
  mongo-cluster:
