<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.32.1" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NATS.Net" Version="2.7.0-preview.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainBlocks.EventStore.Abstractions\DomainBlocks.EventStore.Abstractions.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="commit_record.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
