apiVersion: v1
kind: Secret
metadata:
  name: mongo-connection
  namespace: domain-blocks
type: Opaque
stringData:
  connectionString: "mongodb://mongo-0.mongo.domain-blocks.svc.cluster.local:27017,mongo-1.mongo.domain-blocks.svc.cluster.local:27017,mongo-2.mongo.domain-blocks.svc.cluster.local:27017/?replicaSet=rs0"
