<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DomainBlocks.EventStore.MongoDB.Tests.Integration"/>
    <InternalsVisibleTo Include="DomainBlocks.EventStore.MongoDB.Tests.Unit"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="10.0.2"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2"/>
    <PackageReference Include="Microsoft.Extensions.Resilience" Version="10.2.0"/>
    <PackageReference Include="MongoDB.Driver" Version="3.7.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainBlocks.EventStore.Abstractions\DomainBlocks.EventStore.Abstractions.csproj"/>
  </ItemGroup>

</Project>
