<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="Shouldly"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DomainBlocks.EventStore\DomainBlocks.EventStore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\UserCreated.proto" GrpcServices="None"/>
  </ItemGroup>

</Project>
