<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tests\DomainBlocks.Testing.Integration.EventStore.MongoDB\DomainBlocks.Testing.Integration.EventStore.MongoDB.csproj" />
    <ProjectReference Include="..\DomainBlocks.Benchmarking.EventStore\DomainBlocks.Benchmarking.EventStore.csproj" />
  </ItemGroup>

</Project>