<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1"/>
    <PackageReference Include="MongoDB.Driver" Version="3.5.2" />
    <PackageReference Include="NUnit" Version="4.4.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\DomainBlocks.EventStore.MongoDB.Strict\DomainBlocks.EventStore.MongoDB.Strict.csproj" />
    <ProjectReference Include="..\..\..\src\DomainBlocks.EventStore\DomainBlocks.EventStore.csproj" />
    <ProjectReference Include="..\..\..\src\DomainBlocks.Serialization.MongoDB.Bson\DomainBlocks.Serialization.MongoDB.Bson.csproj" />
    <ProjectReference Include="..\..\DomainBlocks.Testing.Integration.MongoDB\DomainBlocks.Testing.Integration.MongoDB.csproj" />
    <ProjectReference Include="..\..\DomainBlocks.Testing.Integration\DomainBlocks.Testing.Integration.csproj" />
  </ItemGroup>

</Project>