<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tests\DomainBlocks.Testing.Integration.KurrentDB\DomainBlocks.Testing.Integration.KurrentDB.csproj" />
    <ProjectReference Include="..\DomainBlocks.Benchmarking\DomainBlocks.Benchmarking.csproj" />
  </ItemGroup>

</Project>