<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DomainBlocks.Serialization.Google.Protobuf\DomainBlocks.Serialization.Google.Protobuf.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Tools" Version="2.72.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="NUnit" Version="4.4.0"/>
        <PackageReference Include="Shouldly" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\UserCreated.proto"
                  GrpcServices="None"
                  OutputDir="Generated"
                  CompileOutputs="true"/>
    </ItemGroup>

</Project>
