<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\DomainBlocks.EventStore.Abstractions\DomainBlocks.EventStore.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\DomainBlocks.EventStore\DomainBlocks.EventStore.csproj" />
    <ProjectReference Include="..\..\src\DomainBlocks.Serialization.MongoDB.Bson.V2\DomainBlocks.Serialization.MongoDB.Bson.V2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DomainBlocks.Testing.Integration.MongoDB\**\*.cs"
             Exclude="..\DomainBlocks.Testing.Integration.MongoDB\obj\**"
             LinkBase="." />
  </ItemGroup>
  
</Project>
