<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Tools" Version="2.72.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="MongoDB.Driver" Version="3.4.2"/>
        <PackageReference Include="NUnit" Version="4.4.0"/>
        <PackageReference Include="Shouldly" Version="4.3.0"/>
        <PackageReference Include="System.Linq.Async" Version="6.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Proto\UserCreated.proto" GrpcServices="None" OutputDir="Generated" CompileOutputs="true"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DomainBlocks.EventStore.MongoDB\DomainBlocks.EventStore.MongoDB.csproj"/>
        <ProjectReference Include="..\..\src\DomainBlocks.EventStore\DomainBlocks.EventStore.csproj"/>
        <ProjectReference Include="..\..\src\DomainBlocks.Serialization.Google.Protobuf\DomainBlocks.Serialization.Google.Protobuf.csproj"/>
        <ProjectReference Include="..\..\src\DomainBlocks.Serialization.MongoDB.Bson\DomainBlocks.Serialization.MongoDB.Bson.csproj"/>
        <ProjectReference Include="..\..\src\DomainBlocks.Serialization\DomainBlocks.Serialization.csproj"/>
        <ProjectReference Include="..\DomainBlocks.Serialization.Google.Protobuf.Tests\DomainBlocks.Serialization.Google.Protobuf.Tests.csproj"/>
    </ItemGroup>

</Project>
