version: '3.8'

networks:
  shopping-network:
    name: shopping-network
    driver: bridge

services:
  shopping-eventstore:
    image: eventstore/eventstore:23.10.1-bookworm-slim
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - PROJECTION_THREADS=8
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - shopping-network

  shopping-api:
    build:
      context: ../..
      dockerfile: examples/shopping/Shopping.Api/Dockerfile
    image: shopping-api
    ports:
      - "5039:80"
      - "7025:443"
    depends_on:
      - shopping-eventstore
    networks:
      - shopping-network

  shopping-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=shopping-events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-volume-data:/var/lib/postgresql/data
    networks:
      - shopping-network
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  postgres-volume-data:
