<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="Testcontainers.MongoDb" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DomainBlocks.Serialization.Google.Protobuf\DomainBlocks.Serialization.Google.Protobuf.csproj" />
    <ProjectReference Include="..\..\src\DomainBlocks.Serialization.MongoDB.Bson\DomainBlocks.Serialization.MongoDB.Bson.csproj" />
    <ProjectReference Include="..\..\src\DomainBlocks.Serialization.SystemTextJson\DomainBlocks.Serialization.SystemTextJson.csproj" />
    <ProjectReference Include="..\DomainBlocks.Testing.Integration\DomainBlocks.Testing.Integration.csproj" />
  </ItemGroup>

</Project>
