<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\DomainBlocks.EventSourcing\DomainBlocks.EventSourcing.csproj"/>
    <ProjectReference Include="..\..\src\DomainBlocks.EventStore.MongoDB.Generic\DomainBlocks.EventStore.MongoDB.Generic.csproj" />
    <ProjectReference Include="..\..\src\DomainBlocks.Serialization.MongoDB.Bson\DomainBlocks.Serialization.MongoDB.Bson.csproj"/>
    <ProjectReference Include="..\DomainBlocks.Testing.Integration.MongoDB\DomainBlocks.Testing.Integration.MongoDB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MongoDB.Bson" Version="3.7.1" />
    <PackageReference Include="NUnit" Version="4.4.0"/>
    <PackageReference Include="Shouldly" Version="4.3.0"/>
  </ItemGroup>

</Project>