<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" VersionOverride="[2.27.0,3.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainBlocks.Serialization.Abstractions\DomainBlocks.Serialization.Abstractions.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DomainBlocks.Serialization.MongoDB.Bson\**\*.cs"
             Exclude="..\DomainBlocks.Serialization.MongoDB.Bson\obj\**"
             LinkBase="." />
  </ItemGroup>
  
</Project>
