name: Build And Publish

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up EventStoreDB
      run: docker-compose -f docker-compose.test.yml up -d
      working-directory: ./src    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src