name: Build.NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for nbgv

      - name: Set up EventStoreDB
        run: docker-compose -f ./tests/docker-compose.test.yml up -d
        working-directory: .

      - name: 'Calculate version numbers'
        uses: dotnet/nbgv@v0.4
        with:
          setAllVars: true
          path: .

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.300

      - name: Restore dependencies
        run: dotnet restore
        working-directory: .

      - name: Build
        run: dotnet build --no-restore
        working-directory: .

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: .