name: Build And Publish

on:
  push:
    branches:
      - main
      - develop-v1
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for nbgv

      - name: 'Calculate version numbers'
        uses: dotnet/nbgv@v0.4
        with:
          setAllVars: true
          path: .

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.203

      - name: Restore dependencies
        run: dotnet restore
        working-directory: .

      - name: Build
        run: dotnet build --no-restore
        working-directory: .

      - name: Test
        run: |
          pushd ./tests
          docker compose up --quiet-pull -d
          popd
          dotnet test --no-build --verbosity normal
        working-directory: .

      - name: Pack and Publish
        run: |
          dotnet pack -c Release -o ./packages/ --include-symbols --include-source -p:SymbolPackageFormat=snupkg
          dotnet nuget push "./packages/*.nupkg" -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_DOMAINBLOCKS_API_KEY}} --skip-duplicate
        working-directory: .