name: Build And Publish

on:
  push:
    branches:
      - main
      - 'release/**'
  create:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for nbgv

      - name: 'Calculate version numbers'
        uses: dotnet/nbgv@v0.4
        with:
          setAllVars: true
          path: .

      - name: Set up EventStoreDB
        run: docker-compose -f ./tests/docker-compose.test.yml up -d
        working-directory: .

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.300

      - name: Restore dependencies
        run: dotnet restore
        working-directory: .

      - name: Build
        run: dotnet build --no-restore
        working-directory: .

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: .

      - name: Pack and Publish
        run: |
          dotnet pack -c Release -o ./packages/ --include-symbols --include-source -p:SymbolPackageFormat=snupkg
          dotnet nuget push "./packages/*.nupkg" -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_DOMAINBLOCKS_API_KEY}} --skip-duplicate
        working-directory: .