name: Build And Publish

on:
  push:
    branches: 
      - develop
  create:
    branches: 
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # for nbgv
    
    - name: 'Calculate version numbers'
      uses: dotnet/nbgv@v0.4
      with:
        setAllVars: true
        path: ./src
      
    - name: Set up EventStoreDB
      run: docker-compose -f docker-compose.test.yml up -d
      working-directory: ./src    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src

    - name: Remove Docker Compose project # required for nuget pack.
      if: github.event.pull_request.merged == true  
      run: dotnet sln ./DomainBlocks.sln remove Examples/Shopping.DockerCompose.dcproj
      working-directory: ./src
    
    - name: Pack and Publish
      if: github.event.pull_request.merged == true  
      run: |
        dotnet pack -c Release -o ./packages/ --include-symbols --include-source -p:SymbolPackageFormat=snupkg
        dotnet nuget push "./packages/*.nupkg" -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_TEST_KEY}}
      working-directory: ./src